# Generated by Django 4.2.24 on 2025-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_otp',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
