# Generated by Django 4.2.24 on 2025-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_data_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='usr_verify',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
