# Generated by Django 5.2.6 on 2025-10-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_verified_user_data_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='verify',
            new_name='is_verified',
        ),
    ]
