# Generated by Django 5.2.6 on 2025-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_verify_user_data_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
