# Generated by Django 4.2.24 on 2025-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_data_usr_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='expire_otp',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
